const users = [
  {
    id: 1,
    login: "1",
    password: "111",
    name: "Jaina",
    avatar: "https://bit.ly/3TefAYr",
    city: "Dalaran",
    status: "",
    wallpaper: "https://bit.ly/3TuCv1h",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 2,
    login: "2",
    password: "111",
    name: "Lee",
    avatar: "https://bit.ly/3yUfEnR",
    city: "Los Angeles",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3D97FG9",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 3,
    login: "3",
    password: "111",
    name: "Jin",
    avatar: "https://bit.ly/3F8oPoT",
    city: "Los Angeles",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3EO7X6x",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 4,
    login: "4",
    password: "111",
    name: "Eddy",
    avatar: "https://bit.ly/3Tv9DG3",
    city: "Los Angeles",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3ETT9mT",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 5,
    login: "5",
    password: "111",
    name: "Deadpool",
    avatar: "https://bit.ly/3eAJZjY",
    city: "New York",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3SbTSmy",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 6,
    login: "6",
    password: "111",
    name: "Huntress",
    avatar: "https://bit.ly/3D679IX",
    city: "Gotham",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3eICOH4",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 7,
    login: "7",
    password: "111",
    name: "Spider-man",
    avatar: "https://bit.ly/3SQEqgj",
    city: "New York",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3yTi06p",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 8,
    login: "8",
    password: "111",
    name: "Aquaman",
    avatar: "https://bit.ly/3CiSEjt",
    city: "Gotham",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3MG7jtN",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 9,
    login: "9",
    password: "111",
    name: "Natasha",
    avatar: "https://bit.ly/3S0izm7",
    city: "New York",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3s7nhne",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 10,
    login: "10",
    password: "111",
    name: "John",
    avatar: "https://bit.ly/3S4ARSQ",
    city: "Toronto",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3gfmr58",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 11,
    login: "11",
    password: "111",
    name: "Strange",
    avatar: "https://bit.ly/3VgbNLE",
    city: "New York",
    status: "",
    wallpaper: "https://bit.ly/3s498Ht",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 12,
    login: "12",
    password: "111",
    name: "Sonya",
    avatar: "https://bit.ly/3yBHeWH",
    city: "Miami",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3ESTYMB",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 13,
    login: "13",
    password: "111",
    name: "Medivh",
    avatar: "https://bit.ly/3DkRdCV",
    city: "Dalaran",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3g7FvSH",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 14,
    login: "14",
    password: "111",
    name: "Kratos",
    avatar: "https://bit.ly/3SblYy3",
    city: "Toronto",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3D5VCcD",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 15,
    login: "15",
    password: "111",
    name: "Raynor",
    avatar: "https://bit.ly/3CTNn1P",
    city: "Toronto",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3EUYFG0",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 16,
    login: "16",
    password: "111",
    name: "Loki",
    avatar: "https://bit.ly/3CLHi8M",
    city: "New York",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3s52XCK",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 17,
    login: "17",
    password: "111",
    name: "Kitana",
    avatar: "https://bit.ly/3SlLzV2",
    city: "Miami",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3yQQ5UW",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 18,
    login: "18",
    password: "111",
    name: "Anna",
    avatar: "https://bit.ly/3Djrx9K",
    city: "Los Angeles",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3MJ4W9F",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 19,
    login: "19",
    password: "111",
    name: "Ryu",
    avatar: "https://bit.ly/3TXGhk7",
    city: "Tokyo",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3Tfprgn",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 20,
    login: "20",
    password: "111",
    name: "Iron-man",
    avatar: "https://bit.ly/3RGqLZ0",
    city: "New York",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3Te9cQO",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 21,
    login: "21",
    password: "111",
    name: "Hulk",
    avatar: "https://bit.ly/3SJU50S",
    city: "New York",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3D9772X",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 22,
    login: "22",
    password: "111",
    name: "Chun-Li",
    avatar: "https://bit.ly/3gR7CpM",
    city: "Tokyo",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3eF6TY6",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 23,
    login: "23",
    password: "111",
    name: "Liu-Kang",
    avatar: "https://bit.ly/3ROrWVA",
    city: "Miami",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3TC81dT",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 24,
    login: "24",
    password: "111",
    name: "Alisa",
    avatar: "https://bit.ly/3EZdWFw",
    city: "Los Angeles",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3TyIPVy",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 25,
    login: "25",
    password: "111",
    name: "Kung-Lao",
    avatar: "https://bit.ly/3TEcGvz",
    city: "Miami",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3VBmxUX",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 26,
    login: "26",
    password: "111",
    name: "Johnny",
    avatar: "https://bit.ly/3MNm9yJ",
    city: "Miami",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3MJ5Gvt",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 27,
    login: "27",
    password: "111",
    name: "Law",
    avatar: "https://bit.ly/3s31m0z",
    city: "Los Angeles",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3D6v8aO",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 28,
    login: "28",
    password: "111",
    name: "Paul",
    avatar: "https://bit.ly/3VEgxuE",
    city: "Los Angeles",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3ScY8Ca",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 29,
    login: "29",
    password: "111",
    name: "Nina",
    avatar: "https://bit.ly/3yPXKm8",
    city: "Los Angeles",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3MFfeaN",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 30,
    login: "30",
    password: "111",
    name: "Jackie",
    avatar: "https://bit.ly/3TolLJe",
    city: "Miami",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3TzoJKE",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 31,
    login: "31",
    password: "111",
    name: "Wrathion",
    avatar: "https://bit.ly/3s6xvnV",
    city: "Dalaran",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3TuCv1h",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 32,
    login: "32",
    password: "111",
    name: "Joker",
    avatar: "https://bit.ly/3Twy06f",
    city: "Gotham",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3ETT9mT",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 33,
    login: "33",
    password: "111",
    name: "Batman",
    avatar: "https://bit.ly/3TymbMV",
    city: "Gotham",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3SbTSmy",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 34,
    login: "34",
    password: "111",
    name: "Jade",
    avatar: "https://bit.ly/3SjTgeE",
    city: "Miami",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3g7FvSH",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 35,
    login: "35",
    password: "111",
    name: "Logan",
    avatar: "https://bit.ly/3eQE0bf",
    city: "New York",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3EUYFG0",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 36,
    login: "36",
    password: "111",
    name: "Lili",
    avatar: "https://bit.ly/3TIL20q",
    city: "Los Angeles",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3s52XCK",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 37,
    login: "37",
    password: "111",
    name: "Flash",
    avatar: "https://bit.ly/3s4kPhl",
    city: "Gotham",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3MJ4W9F",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 38,
    login: "38",
    password: "111",
    name: "Harley",
    avatar: "https://bit.ly/3CQYzN0",
    city: "Gotham",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3Tfprgn",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 39,
    login: "39",
    password: "111",
    name: "Thor",
    avatar: "https://bit.ly/3SWClzA",
    city: "New York",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3Te9cQO",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 40,
    login: "40",
    password: "111",
    name: "T'Challa",
    avatar: "https://bit.ly/3EHqxgt",
    city: "New York",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3D9772X",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 41,
    login: "41",
    password: "111",
    name: "Sindel",
    avatar: "https://bit.ly/3THGHL2",
    city: "Miami",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3TzoJKE",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 42,
    login: "42",
    password: "111",
    name: "Diana",
    avatar: "https://bit.ly/3SlA5RA",
    city: "Gotham",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3ScY8Ca",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 43,
    login: "43",
    password: "111",
    name: "Hwoarang",
    avatar: "https://bit.ly/3eGgoGl",
    city: "Los Angeles",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3MJ5Gvt",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 44,
    login: "44",
    password: "111",
    name: "Tess",
    avatar: "https://bit.ly/3VCfb3p",
    city: "Dalaran",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3MFfeaN",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 45,
    login: "45",
    password: "111",
    name: "Undisputed",
    avatar: "https://bit.ly/3Es5tuv",
    city: "Toronto",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3D6v8aO",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 46,
    login: "46",
    password: "111",
    name: "Catwoman",
    avatar: "https://bit.ly/3s7txvd",
    city: "Gotham",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3VBmxUX",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 47,
    login: "47",
    password: "111",
    name: "Superman",
    avatar: "https://bit.ly/3RMp2AL",
    city: "Gotham",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3eICOH4",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 48,
    login: "48",
    password: "111",
    name: "Diana",
    avatar: "https://bit.ly/3CMiQmR",
    city: "Dalaran",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3TyIPVy",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
  {
    id: 49,
    login: "49",
    password: "111",
    name: "Steve",
    avatar: "https://bit.ly/3VDbuuj",
    city: "Los Angeles",
    status: "this is character's test status",
    wallpaper: "https://bit.ly/3MJ4W9F",
    about: `Let's imagine that there should be information about this user, but since this is a test description of the character, there is only this simple text.`,
  },
];

export default users;
